typography_spectrum: 0.5
style: the-composer
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9952
analytics:
  google: null
  facebook: null
  twitter: null
name: hp
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose:
  - name: shares
    item: null
    url: null
